#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

dlist=$(ls)

for i in $dlist; do
  echo "$i" | cut -d '-' -f2
done
